#!/usr/bin/env python3
"""
agent_gate.py - A minimal policy gate with cryptographic audit logging.

Workflow:
  1. Agent proposes a structured action.
  2. Policy engine runs deterministic strawman checks.
  3. Operator reviews and accepts or rejects the action.
  4. Decision is committed to an append-only, SHA-256 hashed log file.
"""

import hashlib
import json
import os
import sys
import time
from dataclasses import asdict, dataclass
from typing import Optional, Tuple


@dataclass
class ActionProposal:
    action_id: str
    command: str
    target_path: str
    risk_tier: int  # 1 = Low, 2 = Medium, 3 = High


class PolicyEngine:
    """Enforces basic safety invariants before human review."""

    BLOCKED_PATTERNS = ["rm -rf /", ":(){ :|:& };:", "/dev/sd"]
    PROTECTED_DIRECTORIES = ["/etc", "/boot", "/sys", "C:\\Windows"]

    @classmethod
    def evaluate(cls, proposal: ActionProposal) -> Tuple[bool, str]:
        for pattern in cls.BLOCKED_PATTERNS:
            if pattern in proposal.command:
                return False, f"Blocked: matched hazardous pattern '{pattern}'"

        norm_path = os.path.abspath(proposal.target_path)
        for protected in cls.PROTECTED_DIRECTORIES:
            if norm_path.startswith(os.path.abspath(protected)):
                return False, f"Blocked: access to protected directory '{protected}'"

        if proposal.risk_tier > 3 or proposal.risk_tier < 1:
            return False, "Blocked: invalid risk tier classification"

        return True, "Passed automated policy checks."


class AuditLogger:
    """Maintains an append-only, hash-chained log on disk."""

    def __init__(self, log_path: str = "audit_log.jsonl"):
        self.log_path = log_path
        self.last_hash = self._recover_tip_hash()

    def _recover_tip_hash(self) -> str:
        if not os.path.exists(self.log_path):
            return "0" * 64
        last_line = ""
        with open(self.log_path, "r", encoding="utf-8") as f:
            for line in f:
                if line.strip():
                    last_line = line
        if not last_line:
            return "0" * 64
        try:
            return json.loads(last_line).get("entry_hash", "0" * 64)
        except json.JSONDecodeError:
            return "0" * 64

    def commit(
        self,
        proposal: ActionProposal,
        policy_passed: bool,
        policy_reason: str,
        human_decision: Optional[bool],
    ) -> str:
        timestamp = time.time_ns()
        payload = {
            "prev_hash": self.last_hash,
            "timestamp_ns": timestamp,
            "proposal": asdict(proposal),
            "policy_passed": policy_passed,
            "policy_reason": policy_reason,
            "human_accepted": human_decision,
        }
        serialized = json.dumps(payload, sort_keys=True)
        entry_hash = hashlib.sha256(serialized.encode("utf-8")).hexdigest()
        record = {**payload, "entry_hash": entry_hash}

        with open(self.log_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")

        self.last_hash = entry_hash
        return entry_hash


def main():
    logger = AuditLogger()
    print("[Agent Gate] Initialized. Tip hash:", logger.last_hash[:16] + "...")

    # Simulated candidate actions generated by an agent
    candidates = [
        ActionProposal("act_001", "write_file", "./workspace/report.txt", 1),
        ActionProposal("act_002", "rm -rf /", "/etc", 3),
        ActionProposal("act_003", "delete_file", "./workspace/scratch.tmp", 2),
    ]

    for item in candidates:
        print("\n" + "=" * 50)
        print(f"PROPOSAL [{item.action_id}]: {item.command} -> {item.target_path}")
        print(f"Risk Tier: {item.risk_tier}")

        passed, reason = PolicyEngine.evaluate(item)
        print(f"Policy Result: {reason}")

        human_decision = None
        if passed:
            while True:
                resp = input("Authorize this execution? [y/N]: ").strip().lower()
                if resp in ["y", "yes"]:
                    human_decision = True
                    print("[APPROVED] Executing action.")
                    break
                elif resp in ["n", "no", ""]:
                    human_decision = False
                    print("[REJECTED] Action canceled by user.")
                    break
        else:
            print("[AUTO-REJECTED] Escalation skipped due to policy failure.")

        entry_hash = logger.commit(item, passed, reason, human_decision)
        print(f"Committed to audit log. Entry hash: {entry_hash[:16]}...")


if __name__ == "__main__":
    main()
